### ISSUE TITLE
Animated Sprites Request

### ISSUE THREAD

**Issue by magejosh** [s7092910/Quartz#12]
Meant to do this yesteday. You asked us to open an issue on the git about this. I was dead serious about the intention to use motion graphics as a means of conveying status effects, as such, animated sprite support would be very helpful for this goal. I believe the other request was specific to the use of animated sprites for displaying weapon tiers. 
Honestly I was planning to use the videocontroller, but this would be better on RAM usage i think than that would. At least I'd think it would given the difference in file sizes from mp4 to gif. 
If you do get the time to look into it and it works, awesome. If it doesn't, we haven't lost anything.

**Comment by s7092910** [comment]
Added in 2.1.0
