### ISSUE TITLE
Required Fuel Slot

### ISSUE THREAD

**Issue by SpiderJZMOD** [s7092910/Quartz#14]
Copy the "WorkstationToolGrid" controllers "required_tools=" and "required_tools_only="true"" mechanics into the "WorkstationFuelGrid" controller so that only a stated item would be allowed to be placed into any of the fuel burning slots. This could be used to make select workstations require Gas to work. 

Thank you for your consideration,
Spider

**Comment by s7092910** [comment]
Added in v2.2.0

https://github.com/s7092910/Quartz/releases/tag/v2.2.0
