### ISSUE TITLE
Changing the label in the trader window

### ISSUE THREAD

**Issue by Goblin-aka-Dark** [s7092910/Quartz#17]
**General Stock** is written by default in the title bar of the trader or machine window

![image](https://github.com/s7092910/Quartz/assets/162380803/3f81b609-6376-401c-94a9-2f2788a02ff7)

I would like that when selecting categories, this label would also change according to the name of the selected category, namely:

{category_icon} General Stock:  {category_name}

For example:
fork icon General Stock: Food
![name](https://github.com/s7092910/Quartz/assets/162380803/6868b910-ac8c-4eba-8396-d9ca3edba758)

We add one more to the existing label next to it, a colon is required, for nice look

![name2](https://github.com/s7092910/Quartz/assets/162380803/6dff97f0-00f5-4fe6-a0a6-50800e3b9290)

**Comment by s7092910** [comment]
Added in 2.3.0
