### ISSUE TITLE
Timers: fuel and smelting

### ISSUE THREAD

**Issue by Goblin-aka-Dark** [s7092910/Quartz#20]
### 1. Fuel Window:
I remind about the summary combustion timer, namely the conversion to the format HH:MM:SS instead of the current one MM:SS

![image](https://github.com/s7092910/Quartz/assets/162380803/ea496798-15ae-4115-b44d-0211ca45839d)

### 2. Smelting window
https://www.nexusmods.com/7daystodie/mods/4173
WookieNookie developed a mod that summarizes the melting time for each cell. I would like to have a timer that totals each melt time and displays the sum like with the fuel window. 

![image](https://github.com/s7092910/Quartz/assets/162380803/8171d671-464d-4d9d-acec-a477148ef629)
#
00:24:45 + 01:17:49 = 01:42:34
#
 
![image](https://github.com/s7092910/Quartz/assets/162380803/fc30cbc7-0c15-4829-810f-413d66003778)

### P.S.
 It's likely that WookieNookie's work can be included in the Quartz, if he doesn't mind. Using the ability to use a separate for each cell  and a common timer for melting at the same time doesn't sound bad.
![image](https://github.com/s7092910/Quartz/assets/162380803/1b090dc2-6400-4dab-aeac-795fef2529d7)
Found on discord, it's probably him

**Comment by s7092910** [comment]
This was added in 3.0.0
