### ISSUE TITLE
New Feature Request : windowChallengeEntryDescription objectives hardcode expansion

### ISSUE THREAD

**Issue by magejosh** [s7092910/Quartz#28]
![251570_20240705003601_1](https://github.com/s7092910/Quartz/assets/76418140/06c8992d-2a8f-4904-83bf-26b39efb10c7)
You confirmed our suspicions that controller="ChallengeEntryDescriptionWindow" is hardcoded to 3 options of objectives. It would be nice if we could expand that to at least 5, to fit the request of hellsjanitor. I would like to expand that to a max of 10 options if possible instead. Since there seems to be a lot of room for additional challenge tiers tabs at the top to mod in, room to make really complex ones might be nice, hence up to 10 instead of up to 5 or the vanilla limit of 3.

Whether it makes it or not, I know I appreciate you making quartz for us to use.

**Comment by s7092910** [comment]
Added in v3.1.0.
